name: SuggestionHelper
main: me.yourselvs.MainClass
version: 1.0
commands:
   suggest:
      description: Sends a suggestion to the server.
      usage: /<command>
   sh:
      description: View information about the Suggestion Helper plugin.
      usage: /<command>